name: Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - "v*"

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Linux binary
        run: |
          mkdir dist
          echo "Linux build here" > dist/myapp-linux

      - uses: actions/upload-artifact@v4
        with:
          name: linux-binary
          path: dist/myapp-linux

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build macOS binary
        run: |
          mkdir dist
          echo "Mac build here" > dist/myapp-macos

      - uses: actions/upload-artifact@v4
        with:
          name: mac-binary
          path: dist/myapp-macos

  release:
    needs: [build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: linux-binary
          path: ./dist
      - uses: actions/download-artifact@v4
        with:
          name: mac-binary
          path: ./dist

      - uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
